version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
      # • `./prometheus.yml` refers to `./prometheus.yml` that exists in current directory
      # • `/etc/prometheus/prometheus.yml` refers to where `./prometheus.yml` will be placed inside the container
      - prometheus_data:/prometheus
      # • `prometheus_data` refers to `volumes.prometheus_data` used to make prometheus information presists each restart
      # •  `/prometheus` refers to where should `volumes.grafana_data` will be placed inside the grafana container
    command:
      # tell the prometheus to use `/etc/prometheus/prometheus.yml`
      - '--config.file=/etc/prometheus/prometheus.yml'
      # tell the prometheus to use `/prometheus` as the storage path
      - '--storage.tsdb.path=/prometheus'
      # tell prometheus to reload if we hit `http://localhost:9090/-/reload` to reload changes in `./prometheus.yml`
      - '--web.enable-lifecycle'
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/dashboards:/etc/grafana/main-dashboards
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
volumes:
  prometheus_data:
  grafana_data:
