{
 "title": "Banking-API-Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status_code=~\"5.*\"})",
     "legendFormat": "{{method}} {{path}}-[{{status}}]"
    }
   ]
  },
  {
   "title": "Total Transaction Transfer Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{method=\"POST\", path=\"/v1/transaction\", status_code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(method ,path, le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95 - {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Req / s Per Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval])) by (service, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Req / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[2m])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB SQL Open Conn",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_sql_open_connections{instance=\"172.17.0.1:8080\"}",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Goroutine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"172.17.0.1:8080\", job=\"local-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"172.17.0.1:8080\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"172.17.0.1:8080\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"172.17.0.1:8080\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{pod}} - heap inuse" }
   ]
  }
 ]
}