basePath: /
definitions:
  github_com_arfan21_project-sprint-banking-api_internal_model.BalanceGetResponse:
    properties:
      balance:
        type: number
      currency:
        type: string
    type: object
  github_com_arfan21_project-sprint-banking-api_internal_model.TransactionAddBalanceRequest:
    properties:
      addedBalance:
        minimum: 0
        type: number
      currency:
        type: string
      senderBankAccountNumber:
        maxLength: 30
        minLength: 5
        type: string
      senderBankName:
        maxLength: 30
        minLength: 5
        type: string
      transferProofImg:
        type: string
    required:
    - addedBalance
    - currency
    - senderBankAccountNumber
    - senderBankName
    - transferProofImg
    type: object
  github_com_arfan21_project-sprint-banking-api_internal_model.TransactionGetResponse:
    properties:
      balance:
        type: number
      createdAt:
        type: integer
      source:
        $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_internal_model.TransactionSourceResponse'
      string:
        type: string
      transactionId:
        type: string
      transferProofImg:
        type: string
    type: object
  github_com_arfan21_project-sprint-banking-api_internal_model.TransactionSourceResponse:
    properties:
      bankAccountNumber:
        type: string
      bankName:
        type: string
    type: object
  github_com_arfan21_project-sprint-banking-api_internal_model.TransactionTransferBalanceRequest:
    properties:
      balances:
        minimum: 0
        type: number
      fromCurrency:
        type: string
      recipientBankAccountNumber:
        maxLength: 30
        minLength: 5
        type: string
      recipientBankName:
        maxLength: 30
        minLength: 5
        type: string
    required:
    - balances
    - fromCurrency
    - recipientBankAccountNumber
    - recipientBankName
    type: object
  github_com_arfan21_project-sprint-banking-api_internal_model.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 15
        minLength: 5
        type: string
    required:
    - email
    - password
    type: object
  github_com_arfan21_project-sprint-banking-api_internal_model.UserLoginResponse:
    properties:
      accessToken:
        type: string
      email:
        type: string
      name:
        type: string
    type: object
  github_com_arfan21_project-sprint-banking-api_internal_model.UserRegisterRequest:
    properties:
      email:
        type: string
      name:
        maxLength: 50
        minLength: 5
        type: string
      password:
        maxLength: 15
        minLength: 5
        type: string
    required:
    - email
    - name
    - password
    type: object
  github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.ErrValidationResponse:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse:
    properties:
      data: {}
      message:
        example: Success
        type: string
      meta: {}
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: http://www.synapsis.id
  description: This is a sample server cell for project-sprint-banking-api.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: project-sprint-banking-api
  version: "1.0"
paths:
  /v1/balance:
    get:
      consumes:
      - application/json
      description: Get balance from user account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_internal_model.BalanceGetResponse'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
      summary: Get Balance
      tags:
      - Balance
    post:
      consumes:
      - application/json
      description: Add balance to user account
      parameters:
      - description: Payload balance add request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_internal_model.TransactionAddBalanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
      summary: Add Balance
      tags:
      - Balance
  /v1/balance/history:
    get:
      consumes:
      - application/json
      description: Get transaction from user account
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Limit data
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_internal_model.TransactionGetResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
      summary: Get Transaction
      tags:
      - Balance
  /v1/image:
    post:
      consumes:
      - multipart/form-data
      description: Upload image to s3
      parameters:
      - description: Image file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
      summary: Upload Image
      tags:
      - Image Uploader
  /v1/transaction:
    post:
      consumes:
      - application/json
      description: Transfer balance to bank
      parameters:
      - description: Payload balance transfer request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_internal_model.TransactionTransferBalanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
      summary: Transfer Balance
      tags:
      - Transaction
  /v1/user/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: Payload user Login Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_internal_model.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_internal_model.UserLoginResponse'
              type: object
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
      summary: Login user
      tags:
      - user
  /v1/user/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: Payload user Register Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_internal_model.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_internal_model.UserLoginResponse'
              type: object
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-banking-api_pkg_pkgutil.HTTPResponse'
      summary: Register user
      tags:
      - user
swagger: "2.0"
